apiVersion: v1
kind: Service
metadata:
        name: jenkins
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: port1
  - port: 50000
    protocol: TCP
    targetPort: 50000
    name: port2
  selector:
    app: jenkins
  type: LoadBalancer

